# Site settings
title: Jo Youngheun 
email: joy.neuro@gmail.com
description: "welcome to my gitfolio!"
baseurl: ""
url: "http://joy-neuro.github.io"
twitter_username: Jo_Youngheun
github_username:  joy-neuro

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
